name: Test

on:
  push:
    branches: [ "main", "deneme","deneme2","deneme3","buseboran" ]
  pull_request:
    branches: [ "main", "deneme","deneme2","deneme3","buseboran" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        python test.py
